# Generated by Django 4.0.3 on 2022-11-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainCodeSpace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempts',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
